### PR TITLE
make enmity more readable

### PR DESCRIPTION
**Pull request by ConnorDoesDev**

### CODE REVIEW

**Comment by ConnorDoesDev** [comment]
simple but makes stuff easier lol

**Comment by ConnorDoesDev** [comment]
modified package description
made readme more professional and added a small guide on how to install enmity
overall modified enmity to match discord (use exclamation mark when x installed to make the sentence sound more happy-like, basically discord.)

**Comment by ConnorDoesDev** [comment]
bump :)

**Comment by marioparaschiv** [comment]
Unfortunately, we will not be accepting this as these are very minor changes that we don't feel are required at the moment. We also don't want a big list of contributors on the GitHub repo who each have very little/minor/unnecessary contributions.

**Pull request closed without merging**
